config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/Home'
  

  get 'static_pages/index'
  get 'static_pages/info'
  post 'static_pages/info'

  get 'static_pages/Contactus'
  
 root 'static_pages#Home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 

end

app/controllers/static_pages_controller.rb
require 'open_weather'
class StaticPagesController < ApplicationController
def Home
  end
 def Contactus
 end
 def index
end
 def info
    options = { units: "metric", APPID: '3e08f352ed070370999ae1ee9ddd1dff' }
  	 @city_name = params[:city_name]
  	 @weather_details = OpenWeather::Current.city(@city_name,options)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/Contactus.html.erb
<img src="http://static1.squarespace.com/static/53cede0ae4b0710434ee23ae/t/53d57892e4b0dc5a20673d27/1406498963168/contact-us-banner-1.jpg?format=1500w" alt="Mountain View" style="width:800px;height:150px;">
<p style="color:blue">Name: SACHIN DATTATRAYA JADHAV</p>
<p style="color:blue">Date of Birth: 31/12/1991</p>
<p style="color:blue">Qualification: Master's in Information System</p>
<p style="color:blue">Email id- sjadhav1@murraystate.edu</p>
<p style="color:blue">Contact Number: (270)293-7333</p>


<%= link_to 'Contact Us', static_pages_Contactus_path %>

<%= link_to 'Current Weather', static_pages_index_path %>

app/views/static_pages/Home.html.erb
<h1 style="color:red">Welcome to my Website</h1>

<img src="http://kingfahadmosque.org/wp-content/uploads/2012/03/website-welcome.jpg" alt="Mountain View" style="width:380px;height:180px;">

  <p style="color:blue"> 

<%= link_to 'Contact Us', static_pages_Contactus_path %>

<%= link_to 'Current Weather', static_pages_index_path %>

app/views/static_pages/index.html.erb
<h1>weather Report</h1>

<%= form_tag ('info') do%>
	<%= label_tag 'City' %>
	<%= text_field_tag 'city_name' %>
	<%= submit_tag 'Get Data'%>
<%end%>


<%= link_to 'Contact Us', static_pages_Contactus_path %>

<%= link_to 'Home', static_pages_Home_path %>

app/views/static_pages/info.html.erb
<h1>Welcome to Weather Page</h1>
<h1>Listing Weather Details</h1>
<%if @weather_details["cod"] == "404"%>
    <h1><%=@weather_details["message"]%></h1>
    <%else%>
        <table>
          <thead>
            <tr>
              <th>Description</th>
              <th>Temparature</th>
              <th>Pressure</th>
              <th>Humidity</th>
              <th>Min Temparature</th>
              <th>Max Temparature</th>
              <th>City</th>
            </tr>
          </thead>
        
          <tbody>
              <tr>
                <td><%= @weather_details["weather"][0]["description"]%></td>
                <td><%= @weather_details["main"]["temp"]%></td>
                <td><%= @weather_details["main"]["pressuee"]%></td>
                <td><%= @weather_details["main"]["humidity"]%></td>
                <td><%= @weather_details["main"]["temp_min"]%></td>
                <td><%= @weather_details["main"]["temp_max"]%></td>
                <td><%= @weather_details["name"]%></td>
              </tr>
          </tbody>
        </table>
        
        <br>
<%end%>
<%= link_to 'Home', static_pages_Home_path %>
<%= link_to 'Contact Us', static_pages_Contactus_path %>

<%= link_to 'Current Weather', static_pages_index_path %>